### ISSUE TITLE
[Gestionnaires] création convention impossible quand un étudiant change de cursus (et donc de centre de gestion)

### ISSUE THREAD

**Issue by DidierUCA** [EsupPortail/esup-stage#87]
Bonjour,

Quand un gestionnaire veut créer une convention pour un étudiant et que ce dernier, a passé des années précédents dans d'autres formations (composantes ou étapes -vet-) gérées par d'autres centres de gestion, il lui est impossible de créer une convention.

Sur la page de l'étudiant, le gestionnaire voit ceci : 
![image](https://github.com/EsupPortail/esup-stage/assets/159555869/77c0d046-8e2e-4242-8bfe-31fc3620bb45)

Dans les logs de l'application, on tombe face à un _NullPointerException_
```24-02-14 10:24:23.218  INFO 997056 --- [0-8009-exec-108] o.e.e.service.apogee.ApogeeService       : Apogee /anneesIa parametres: {{codEtud=21900630}}
2024-02-14 10:24:23.239  INFO 997056 --- [0-8009-exec-125] o.e.e.service.apogee.ApogeeService       : Apogee /etudiantRef parametres: {{codEtud=21900630, annee=2023}}
2024-02-14 10:24:23.266  INFO 997056 --- [0-8009-exec-108] o.e.e.service.apogee.ApogeeService       : Apogee /etapesByEtudiantAndAnnee parametres: {{codEtud=21900630, annee=2022}}
2024-02-14 10:24:27.119  INFO 997056 --- [0-8009-exec-108] o.e.e.service.apogee.ApogeeService       : Apogee /etapesByEtudiantAndAnnee parametres: {{codEtud=21900630, annee=2023}}
2024-02-14 10:24:27.452 ERROR 997056 --- [0-8009-exec-108] o.s.b.w.servlet.support.ErrorPageFilter  : Forwarding to error page from request [/api/etudiants/21900630/apogee-inscriptions] due to exception [null]

java.lang.NullPointerException: null
        at org.esup_portail.esup_stage.service.apogee.ApogeeService.lambda$getInscriptions$7(ApogeeService.java:291) ~[classes/:2.0.1]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[na:na]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
(...)
```

Après tests et échanges (_cf._ messages sur la liste esup-stage en date du 14 et 15 février 2024), si le gestionnaire n'est pas également gestionnaire du passif de formation de l'étudiant (c-a-d que pour débloquer la situation il a fallu que je mette le gestionnaire sur un centre de gestion où était inscrit l'étudiant + autoriser la création de conventions sur l'année n-1, ce qui n'est pas du tout **tenable** en terme de gestion), il se retrouve dans l'impossibilité de créer des conventions de stage. 

Cordialement,
D. Chabaud

**Comment by csylvanie** [comment]
Bonjour,
Il y a un paramètre dans le centre de gestion qui permet au gestionnaire de créer une convention sur l'année antérieure. Normalement ce paramètre prend la valeur true ou false en base de données. Pourtant dans votre cas, la valeur actuelle est null. Une piste de correction serait d'activer le paramètre "Autoriser les gestionnaires à créer des conventions sur l'année universitaire précédente" situé dans l'onglet "Paramètres du centre" de chaque centre de gestion.
![image](https://github.com/EsupPortail/esup-stage/assets/127086660/546919a3-6726-4f52-81c4-49294c27c49b)

**Comment by DidierUCA** [comment]
Bonjour,

Merci Claude pour cette réponse. 

Sur la convention "à problème", j'ai coché autoriser les gestionnaires (sans rajouter pour autant la gestionnaire en question), elle a pu créer la convention. C'était un **nouveau** centre de gestion que j'avais créé (donc par défaut prendrait-il la valeur _null_ ? ) : code source lors de la création de nouveau centre de gestion à vérifier ?

Je poursuis mes tests : je n'ai aucun centre de gestion avec la valeur null pour le champ recupInscriptionAnterieure (mais bien 0 ou 1).

Cordialement,
D. Chabaud

**Comment by ssound** [comment]
À corriger : à la création d'un nouveau centre, le booléen reste à null.
Il faudrait initialiser tous les booléens pour avoir soit 0 soit 1 en base de données.

**Comment by yktorza** [comment]
Pour info : il faudra effectivement initialiser tous les booléens pour avoir soit 0 soit 1 en base de données, sachant que le problème est susceptible de se poser aussi pour les champs validationPedagogique, validationConvention et verificationAdministrative (de la table Centre de gestion). Une des conséquences peut être l'impossibilité de supprimer des conventions non validées (cf. mon mail de jour sur la liste, le 29/11/2024 à 11h34)

**Comment by csylvanie** [comment]
Bonjour @DidierUCA  La version 3.0.0 à venir prendre en charge la correction de ce problème.
